apiVersion: v1
kind: Pod
spec:
  containers:
  - name: gabps
    image: gabps:bede
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 4
        memory: 20Gi
      requests:
        cpu: 4
        memory: 20Gi
    command: ["./test.sh"]