apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: cavol
      hostPath:
        path: "/bede-data/workloads/KMEANS"
  containers:
  - name: gabps
    image: gabps:bede
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 4
        memory: 20Gi
      requests:
        cpu: 4
        memory: 20Gi
    command: ["./test.sh"]